# Generated by Django 6.0.4 on 2026-06-22 23:31

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_year', models.IntegerField(unique=True)),
                ('end_year', models.IntegerField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('end_year', django.db.models.expressions.CombinedExpression(models.F('start_year'), '+', models.Value(1)))), name='generation_lasts_one_year'), models.UniqueConstraint(fields=('end_year',), name='unique_end_year')],
            },
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('1v1', '1 tegen 1'), ('1v2', '1 tegen 2'), ('2v2', '2 tegen 2'), ('4v4', '4 tegen 4')], max_length=3, unique=True)),
                ('players_team_1', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (4, 'Four')])),
                ('players_team_2', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (4, 'Four')])),
                ('elo_eligible', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('match_type', '1v1'), _negated=True), models.Q(('players_team_1', 1), ('players_team_2', 1)), _connector='OR'), name='matchtype_1v1_sizes'), models.CheckConstraint(condition=models.Q(models.Q(('match_type', '1v2'), _negated=True), models.Q(('players_team_1', 1), ('players_team_2', 2)), _connector='OR'), name='matchtype_1v2_sizes'), models.CheckConstraint(condition=models.Q(models.Q(('match_type', '2v2'), _negated=True), models.Q(('players_team_1', 2), ('players_team_2', 2)), _connector='OR'), name='matchtype_2v2_sizes'), models.CheckConstraint(condition=models.Q(models.Q(('match_type', '4v4'), _negated=True), models.Q(('players_team_1', 4), ('players_team_2', 4)), _connector='OR'), name='matchtype_4v4_sizes')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_played', models.DateTimeField()),
                ('timestamp_uploaded', models.DateTimeField()),
                ('score_team_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('score_team_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('ranked', models.BooleanField(default=False)),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualitybutchertv.matchtype', to_field='match_type')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=32)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('elo_gain', models.FloatField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualitybutchertv.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualitybutchertv.player')),
            ],
        ),
        migrations.CreateModel(
            name='ELO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.FloatField(default=1500)),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qualitybutchertv.matchtype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualitybutchertv.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('score_team_1__gte', 0)), name='match_score_team_1_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('score_team_2__gte', 0)), name='match_score_team_2_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('score_team_1__lte', 12), ('score_team_2__lte', 12)), name='match_scores_max_12'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('score_team_1', 0), ('score_team_2', 0), _negated=True), name='match_not_both_zero'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ranked', True), _negated=True), models.Q(models.Q(('score_team_1__gte', 10), ('score_team_2__gte', 10), _connector='OR'), ('score_team_1__lte', 12), ('score_team_2__lte', 12), models.Q(('score_team_1__lte', 9), ('score_team_2__lte', 9), _connector='OR'), models.Q(('score_team_1', models.F('score_team_2')), _negated=True)), _connector='OR'), name='ranked_match_score_rules'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipant',
            constraint=models.UniqueConstraint(fields=('player', 'match'), name='unique_player_match'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('team', 1), ('team', 2), _connector='OR'), name='participant_team_1_or_2'),
        ),
        migrations.AddConstraint(
            model_name='elo',
            constraint=models.UniqueConstraint(fields=('player', 'match_type'), name='unique_player_matchtype_elo'),
        ),
    ]
