# Generated by Django 6.0.4 on 2026-05-19 11:48

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('1v1', '1 tegen 1'), ('1v2', '1 tegen 2'), ('2v2', '2 tegen 2'), ('4v4', '4 tegen 4')], max_length=3, unique=True)),
                ('players_team_1', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (4, 'Four')])),
                ('players_team_2', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (4, 'Four')])),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_year', models.IntegerField(unique=True)),
                ('end_year', models.IntegerField(blank=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('end_year', django.db.models.expressions.CombinedExpression(models.F('start_year'), '+', models.Value(1)))), name='generation_lasts_one_year'), models.UniqueConstraint(fields=('end_year',), name='unique_end_year')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_played', models.DateTimeField()),
                ('timestamp_uploaded', models.DateTimeField()),
                ('score_team_1', models.SmallIntegerField()),
                ('score_team_2', models.SmallIntegerField()),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualitybutchertv.matchtype', to_field='match_type')),
            ],
        ),
        migrations.CreateModel(
            name='MockRSKMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=48, null=True)),
                ('interject', models.CharField(blank=True, max_length=16, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('residence', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.\nUp to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Geboortedatum')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qualitybutchertv.generation', to_field='start_year')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=32)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qualitybutchertv.mockrskmember')),
            ],
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.SmallIntegerField()),
                ('elo_gain', models.FloatField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualitybutchertv.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualitybutchertv.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'match'), name='unique_player_match')],
            },
        ),
        migrations.CreateModel(
            name='ELO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.FloatField(default=1500)),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qualitybutchertv.matchtype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualitybutchertv.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'match_type'), name='unique_player_matchtype_elo')],
            },
        ),
    ]
