# Generated by Django 6.0.4 on 2026-06-01 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitybutchertv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchtype',
            name='elo_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generation',
            name='end_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team_1',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team_2',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='team',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='mockrskmember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('score_team_1__gte', 0)), name='match_score_team_1_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('score_team_2__gte', 0)), name='match_score_team_2_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('score_team_1__lte', 12), ('score_team_2__lte', 12)), name='match_scores_max_12'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('score_team_1', 0), ('score_team_2', 0), _negated=True), name='match_not_both_zero'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ranked', True), _negated=True), models.Q(models.Q(('score_team_1__gte', 10), ('score_team_2__gte', 10), _connector='OR'), ('score_team_1__lte', 12), ('score_team_2__lte', 12), models.Q(('score_team_1__lte', 9), ('score_team_2__lte', 9), _connector='OR'), models.Q(('score_team_1', models.F('score_team_2')), _negated=True)), _connector='OR'), name='ranked_match_score_rules'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('team', 1), ('team', 2), _connector='OR'), name='participant_team_1_or_2'),
        ),
        migrations.AddConstraint(
            model_name='matchtype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('match_type', '1v1'), _negated=True), models.Q(('players_team_1', 1), ('players_team_2', 1)), _connector='OR'), name='matchtype_1v1_sizes'),
        ),
        migrations.AddConstraint(
            model_name='matchtype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('match_type', '1v2'), _negated=True), models.Q(('players_team_1', 1), ('players_team_2', 2)), _connector='OR'), name='matchtype_1v2_sizes'),
        ),
        migrations.AddConstraint(
            model_name='matchtype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('match_type', '2v2'), _negated=True), models.Q(('players_team_1', 2), ('players_team_2', 2)), _connector='OR'), name='matchtype_2v2_sizes'),
        ),
        migrations.AddConstraint(
            model_name='matchtype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('match_type', '4v4'), _negated=True), models.Q(('players_team_1', 4), ('players_team_2', 4)), _connector='OR'), name='matchtype_4v4_sizes'),
        ),
    ]
