# Generated by Django 5.2.4 on 2026-07-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitybutchertv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('1v1', '1 tegen 1'), ('1v2', '1 tegen 2'), ('2v2', '2 tegen 2'), ('4v4', '4 tegen 4')], max_length=3),
        ),
        migrations.AlterField(
            model_name='elo',
            name='match_type',
            field=models.CharField(choices=[('1v1', '1 tegen 1'), ('1v2', '1 tegen 2'), ('2v2', '2 tegen 2'), ('4v4', '4 tegen 4')], max_length=3),
        ),
        migrations.DeleteModel(
            name='MatchType',
        ),
    ]
