# Generated by Django 6.0.4 on 2026-06-22 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(verbose_name='gebruikersnaam')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='voornaam')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='achternaam')),
            ],
            options={
                'verbose_name': 'gebruiker',
                'verbose_name_plural': 'gebruikers',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Yeargroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='jaarlaag')),
                ('name', models.CharField(max_length=25, verbose_name='naam')),
                ('description', models.TextField(blank=True, null=True, verbose_name='omschrijving')),
            ],
            options={
                'verbose_name': 'jaargroep',
                'verbose_name_plural': 'jaargroepen',
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_since', models.PositiveSmallIntegerField(verbose_name='lid sinds')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
            options={
                'verbose_name': 'profiel',
                'verbose_name_plural': 'profielen',
                'ordering': ('user__first_name', 'user__last_name'),
            },
        ),
    ]
